config/routes.rb
Rails.application.routes.draw do
  devise_for :adverts
  resources :ads
  # get 'home/index'
  get 'home/Ads'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/advert.rb
class Advert < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]

  # GET /ads or /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1 or /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:Caption, :Ad_data)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
  <br/>
    <%= form.text_field :Caption, class:"form-control", placeholder:"Caption" %>
  </div>

  <div class="field form-group">
   <br/>
    <%= form.text_field :Ad_data, class:"form-control", placeholder:"Ads Data" %>
  </div>
<br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>
<br/>
<%= link_to 'Show', @ad, class:"btn btn-secondary" %> 
<%= link_to 'Back', ads_path, class:"btn btn-dark" %>

app/views/ads/index.html.erb
<h1>Ads</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Caption</th>
      <th>Ad data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.Caption %></td>
        <td><%= ad.Ad_data %></td>
        <td><%= link_to 'Show', ad %></td>
        <td><%= link_to 'Edit', edit_ad_path(ad) %></td>
        <td><%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_ad_path, class:"btn btn-secondary" %>

app/views/ads/new.html.erb
<br/><h1>New Advert</h1>

<%= render 'form', ad: @ad %>
<br/>
<%= link_to 'Back', ads_path, class:"btn btn-dark" %>

app/views/ads/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @ad.Caption %></h5>
    <p class="card-text"><%= @ad.Ad_data %></p>
    <%= link_to 'Edit', edit_ad_path(@ad), class:"btn btn-secondary" %>
    <%= link_to 'Back', ads_path, class:"btn btn-dark" %>
  </div>
</div>

app/views/home/Ads.html.erb
<h2>This page is under development, Please click back button of the create ad navigation to see,create,edit and delete ads. </h2>
<p>Thank You<p>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Advert', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
      <% if advert_signed_in? %>
        <%= link_to 'Ads', home_Ads_path, class:"nav-link" %>
        <%= link_to 'Create Ad', new_ad_path, class:"nav-link" %>
        <%= link_to 'Sign Out', destroy_advert_session_path, method: :delete, class:"nav-link" %>
      <% else %>
        <%= link_to 'Register', new_advert_registration_path, class:"nav-link" %>
        <%= link_to 'Sign In', new_advert_session_path, class:"nav-link" %>
      <% end %> 
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to Advertisement Posts.</h1>
<p>Please Register and Login to see and create ads.</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    # <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    # <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Advert</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = "container">
    <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>